# tasks file for init_ec2_hosts

- include: python.yml
  tags: python

- include: build_iam.yml
  tags: build_iam

- include: build_vpc.yml
  tags: build_vpc

- include: build_ec2.yml
  tags: build_ec2